// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc4oH6mSuu5otqIddaRL_I0TY1m9-wBuk',
    appId: '1:692831283157:web:3aca2455fdfef805683f5c',
    messagingSenderId: '692831283157',
    projectId: 'my-app-73197',
    authDomain: 'my-app-73197.firebaseapp.com',
    storageBucket: 'my-app-73197.appspot.com',
    measurementId: 'G-BVHQRG592Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtkrdGMz5CDM-ayVP1Wt8bcptD1B12VI',
    appId: '1:692831283157:android:1e41f3b07b372c70683f5c',
    messagingSenderId: '692831283157',
    projectId: 'my-app-73197',
    storageBucket: 'my-app-73197.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcmYH5JaKjoFsK1k-yNPDRZvjQMUsQHqE',
    appId: '1:692831283157:ios:608a1f81d0d291e2683f5c',
    messagingSenderId: '692831283157',
    projectId: 'my-app-73197',
    storageBucket: 'my-app-73197.appspot.com',
    iosClientId:
        '692831283157-bas8gsgjljhq6msu3r3fv1j51ah60fen.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcmYH5JaKjoFsK1k-yNPDRZvjQMUsQHqE',
    appId: '1:692831283157:ios:608a1f81d0d291e2683f5c',
    messagingSenderId: '692831283157',
    projectId: 'my-app-73197',
    storageBucket: 'my-app-73197.appspot.com',
    iosClientId:
        '692831283157-bas8gsgjljhq6msu3r3fv1j51ah60fen.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
